djangoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('exhibit/', include('exhibit.urls')),
    path("oauth/", include('social_django.urls', namespace='social'))

]

if settings:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exhibit/urls.py
from django.urls import path, include
from . import views


urlpatterns = [

    path('', views.index, name='index'),
    path('user/<username>', views.user, name='user'),
    path('me/', views.me, name='me'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_request, name='login'),
    path("logout", views.logout_request, name="logout"),
    path("add/", views.photo_add, name="photo-add"),
    path("search/", views.search, name="search"),
    path("follow/", views.follow, name="follow"),
    path("contacts/", views.contacts, name="contacts"),
    path("contact_form/", views.send_message, name="send_message"),
    path("newsletter/", views.newsletter, name="newsletter"),
    path("inmails/", views.inmails, name="inmails"),
    path("inmail/<int:inmail_id>", views.inmail, name="inmail"),
    path("detail/<int:img_id>", views.detail, name="detail"),
    path("like/<int:img_id>", views.like, name="like"),


]

exhibit/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils import timezone



class Photo(models.Model):
    add_date = models.DateTimeField(auto_now_add=True)
    photo_title = models.CharField(max_length=100)
    photo_file = models.FileField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    photo_like = models.IntegerField(default=0)

    def was_published_recently(self):
        return self.add_date >= timezone.now() - datetime.timedelta(days=1)


    def __str__(self):
        return self.photo_title

class Like(models.Model):
    like_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    like_photo = models.ForeignKey(Photo, on_delete=models.CASCADE, blank=True)

class Contact(models.Model):
    user_from = models.ForeignKey(User, related_name="rel_from_set", on_delete=models.CASCADE)
    user_to = models.ForeignKey(User, related_name="rel_to_set", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} obserwuje {}'.format(self.user_from, self.user_to)

User.add_to_class('following', models.ManyToManyField('self', through=Contact, related_name="followers", symmetrical=False))

class SendMessage(models.Model):
    userfrom = models.ForeignKey(User, related_name="rel_from", on_delete=models.CASCADE)
    useremail = models.EmailField(default='type@youremail.here')
    msgtitle = models.CharField(max_length=100, default="Wiadomość ze strony")
    msg = models.TextField()
    senton = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Wiadomość od {} wysłana {}, temat: {} '.format(self.userfrom, self.senton, self.msgtitle)


class NewsletterUsers(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    useremail = models.EmailField(default='type@yourmail.here')
    rodo = models.BooleanField(default=False, blank=False, verbose_name="Czy zgadasz się na newsletter?")
    news_from = models.DateTimeField(auto_now_add=True)


class InMail(models.Model):
    from_user = models.ForeignKey(User, related_name="from_user", on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name="to_user", on_delete=models.CASCADE)
    send = models.DateTimeField(auto_now_add=True, db_index=True)
    title_txt = models.CharField(max_length=100, default="Nowa wiadomość InMail")
    message_txt = models.TextField()


class Vote(models.Model):
    user_vote = models.ForeignKey(User, related_name="user_vote", on_delete=models.CASCADE)
    photo_vote = models.ForeignKey(Photo, related_name="photo_vote", on_delete=models.CASCADE)
    liked_on = models.DateTimeField(auto_now_add=True, db_index=True)

exhibit/forms.py
from django import forms
from .models import Photo, SendMessage, NewsletterUsers, InMail

class PostForm(forms.ModelForm):

    class Meta:
        model = Photo
        fields = ('photo_title', 'photo_file')

class MsgForm(forms.ModelForm):
    class Meta:
        model = SendMessage
        fields = ('useremail', 'msgtitle', 'msg')


class NewsletterForm(forms.ModelForm):
    class Meta:
        model = NewsletterUsers
        fields = ('useremail', 'rodo')

class InMailForm(forms.ModelForm):
    class Meta:
        model = InMail
        fields = ('to_user', 'title_txt', 'message_txt')

exhibit/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import PostForm, MsgForm, NewsletterForm, InMailForm
from .models import *
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect


def index(request):
    username = None
    try:
        if request.user.is_authenticated:
            username = request.user.username
    except: pass
    photos = Photo.objects.all().order_by('-photo_like')

    context = {'photos' : photos,
               'username': username}
    return render(request, 'exhibit/index.html', context)


def user(request, username):
    user = User.objects.get(username=username)
    photos = Photo.objects.filter(owner=user.pk)
    context = {'photos' : photos}
    return render(request, 'exhibit/user_p.html', context)
    # u = User.objects.all()
    # return HttpResponse(u)

@login_required
def me(request):
    username = None
    if request.user.is_authenticated:
        username = request.user.username
        user = User.objects.get(username=username)
        photos = Photo.objects.filter(owner=user.pk)
        context = {'photos': photos,
                  'username': username}
        return render(request, 'exhibit/user_p.html', context)
    else:
        return render(request, 'exhibit/notlogin.html')



def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'exhibit/signup.html', {'form': form})

def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                return render(request, "exhibit/login.html", {"form":form})
        else:
            return render(request, "exhibit/login.html", {"form": form})
    form = AuthenticationForm()
    return render(request, "exhibit/login.html", {"form":form})


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("index")

@login_required
def photo_add(request):
    if request.user.is_authenticated:
        username= None
        username = request.user.username
        if request.method == "POST":
            form = PostForm(request.POST, request.FILES)
            if form.is_valid():
                photo = form.save(commit=False)
                if request.user.is_authenticated:
                    username = request.user.username
                    user = User.objects.get(username=username)
                    photo.owner = user
                photo.save()
                # return redirect('post_detail', pk=photo.pk)
                return redirect('me')
        else:
            form = PostForm()
        return render(request, 'exhibit/add_photo.html', {'form': form, 'username': username})
    else:
        return render(request, 'exhibit/notlogin.html')


def search(request):
    username = None
    try:
        if request.user.is_authenticated:
            username = request.user.username
    except:
        pass
    query = request.GET.get('q')
    if query:
        users = User.objects.filter(username__contains=query)
        photos = Photo.objects.filter(photo_title__contains=query)
        context = {'users': users, 'photos': photos, 'username': username}
        return render(request, 'exhibit/results.html', context )
    else:
        return render(request, 'exhibit/results.html', context={'empty':'empty'})

@login_required
def follow(request):
    if request.user.is_authenticated:

        f = request.GET.get('f')
        user_to_follow = User.objects.get(pk=f)
        if request.user.is_authenticated:
            username = request.user.username
            user_from = User.objects.get(username=username)
        c = Contact( user_from=user_from, user_to=user_to_follow)
        c.save()

        return redirect('contacts')
    else:
        return render(request, 'exhibit/notlogin.html')
@login_required
def contacts(request):
    if request.user.is_authenticated:
        username = request.user.username
        user_from = User.objects.get(username=username)
        q = Contact.objects.filter(user_from=user_from)
        context = {'contacts': q, 'username': username}
        return render(request, 'exhibit/contacts.html', context)
    else:
        return render(request, 'exhibit/notlogin.html')

@login_required
def send_message(request):
    if request.user.is_authenticated:
        username= None
        username = request.user.username
        if request.method == "POST":
            form = MsgForm(request.POST, request.FILES)
            if form.is_valid():
                msg = form.save(commit=False)
                if request.user.is_authenticated:
                    username = request.user.username
                    user = User.objects.get(username=username)
                    msg.userfrom = user
                    subject = form.cleaned_data['msgtitle']
                    from_email = form.cleaned_data['useremail']
                    msg_to_send = "Wiadomość od: " + from_email + " treść: " + form.cleaned_data['msg']
                    message = msg_to_send
                    msg.save()
                    try:
                        send_mail(subject, message, from_email, ['czesc@ithinkso.pl'])
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return render(request, 'exhibit/success.html',{'form': form, 'username': username} )
                return render(request, 'exhibit/success.html',{'form': form, 'username': username} )

                msg.save()
                # return redirect('post_detail', pk=photo.pk)
                return render(request, 'exhibit/success.html',{'form': form, 'username': username} )
        else:
            form = MsgForm()
        return render(request, 'exhibit/contact_form.html', {'form': form, 'username': username})
    else:
        return render(request, 'exhibit/notlogin.html')

@login_required
def newsletter(request):
    if request.user.is_authenticated:

        username = None
        username = request.user.username
        if request.method == "POST":
            form = NewsletterForm(request.POST)
            rodo = request.POST.get('rodo', '')
            print('log')
            print(rodo)
            if rodo == '':
                return render(request, 'exhibit/bad.html', {'form':form, 'username':username})
            if form.is_valid():
                newsletter = form.save(commit=False)
                if request.user.is_authenticated:
                    username = request.user.username
                    user = User.objects.get(username=username)
                    newsletter.user = user
                newsletter.save()
                # return redirect('post_detail', pk=photo.pk)
                return render(request, 'exhibit/success.html')
        else:
            form = NewsletterForm()
        return render(request, 'exhibit/newsletter.html', {'form': form, 'username': username})
    else:
        return render(request, 'exhibit/notlogin.html')

@login_required
def inmails(request):
    if request.user.is_authenticated:
        username = None
        username = request.user.username
        username_getpk = User.objects.get(username=username)
        inmails = InMail.objects.filter(to_user=username_getpk)
        if request.method == "POST":
            form = InMailForm(request.POST)
            if form.is_valid():
                inmail = form.save(commit=False)
                if request.user.is_authenticated:
                    username = request.user.username
                    user = User.objects.get(username=username)
                    inmail.from_user = user
                inmail.save()
                return render(request, 'exhibit/inmail.html', {'form': form, 'username': username, 'inmails': inmails, 'success':True, 'username': username})
        else:
            form = InMailForm()
        return render(request, 'exhibit/inmail.html', {'form': form, 'username': username, 'inmails':inmails})
    else:
        return render(request, 'exhibit/notlogin.html')

@login_required
def inmail(request, inmail_id):
    if request.user.is_authenticated:
        try:
            username = None
            inmail_id = inmail_id
            username = request.user.username
            username_getpk = User.objects.get(username=username)
            inmails = InMail.objects.filter(to_user=username_getpk)
            inmail = InMail.objects.get(id=inmail_id, to_user=username_getpk)

            return render(request, 'exhibit/inmail_.html', {'username': username, 'inmail': inmail, 'inmails':inmails})
        except InMail.DoesNotExist:
            username = None
            username = request.user.username

exhibit/templates/exhibit/add_photo.html
{% extends 'base.html' %}

{% block content %}
 <div class="container-fluid">
 <div class="row">
     <div class="col-sm"></div>
     <div class="col-sm">




         <h2>Dodaj zdjęcie</h2>
     <div class="form-group fluid">
  <form method="post" class="post-form" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form.as_p }}
      </p>
    <button type="submit" class="btn btn-outline-success btn-block">Dodaj</button>
  </form></div>



     <br />


     </div>
     <div class="col-sm"></div>
 </div>
 </div>
                <script>
  $("#id_photo_title").addClass("form-control");
  $("#id_photo_file").addClass("btn-secondary");
  $("#id_password2").addClass("form-control");
                </script>
{% endblock %}
        </div>

exhibit/templates/exhibit/bad.html
{% extends 'base.html' %}

{% block content %}
 <div class="container-fluid">
 <div class="row">
     <div class="col-sm"></div>
     <div class="col-sm">

<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <strong>Holy guacamole! {{ username }}</strong> Musisz wyrazić zgodę RODO.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
         <h2>Prześlij wiadomość</h2>
     <div class="form-group fluid">
  <form method="post" class="post-form" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form.as_p }}
      </p>
    <button type="submit" class="btn btn-outline-success btn-block">Dodaj</button>
  </form></div>



     <br />


     </div>
     <div class="col-sm"></div>
 </div>
 </div>
                <script>
  $("#id_useremail").addClass("form-control");
  $("#id_msgtitle").addClass("form-control");
  $("#id_password2").addClass("form-control");
  $("#id_msg").addClass("form-control");
                </script>
{% endblock %}
        </div>

exhibit/templates/exhibit/contact_form.html
{% extends 'base.html' %}

{% block content %}
 <div class="container-fluid">
 <div class="row">
     <div class="col-sm"></div>
     <div class="col-sm">

         <h2>Prześlij wiadomość</h2>
     <div class="form-group fluid">
  <form method="post" class="post-form" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form.as_p }}
      </p>
    <button type="submit" class="btn btn-outline-success btn-block">Dodaj</button>
  </form></div>



     <br />


     </div>
     <div class="col-sm"></div>
 </div>
 </div>
                <script>
  $("#id_useremail").addClass("form-control");
  $("#id_msgtitle").addClass("form-control");
  $("#id_password2").addClass("form-control");
  $("#id_msg").addClass("form-control");
                </script>
{% endblock %}
        </div>

exhibit/templates/exhibit/contacts.html
{% extends 'base.html' %} {% block content %}

    {% if alert %}
    {{ alert }}
    {% endif %}

    {% if contacts %}

        <div class="container">
        <div class="row">
            <div class="col-sm"></div>
            <div class="col-sm">
                {% for contact in contacts %}
                <div class="card border-dark mb-3" style="max-width: 18rem;">
  <div class="card-header">Twój przyjaciel:</div>
  <div class="card-body text-dark">
    <h5 class="card-title">{{ contact.user_to }}</h5>
    <p class="card-text">Jesteście znajomymi od {{ contact.created }}</p>
  </div>
</div>
                {% endfor %}
            </div>
            <div class="col-sm"></div>
        </div>
        </div>

        {% else %}
    <div class="container">
        <div class="row">
            <div class="col-sm"></div>
            <div class="col-sm">

                <div class="alert alert-danger" role="alert">
  Nie masz jeszcze żadnych znajomych.
</div>

            </div>
            <div class="col-sm"></div>
        </div>
        </div>
    {% endif %}


{% endblock %}

exhibit/templates/exhibit/index.html
{% extends 'base.html' %} {% block content %}


    {% if photos %}
{#Jumbotron#}
<style>
.zoom:hover {
    max-width: 100%;
    transition: transform 0.3s ease-in-out;
    transform: scale(1.1);
}

</style>
                    {% if user.is_authenticated %}

    <div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Holy guacamole <i>{{ username }}!</i></strong> Bądź na bieżąco, zapisz się na nasz newsletter! <a style="color:#856404"href="{% url 'newsletter'%}"><strong>Chcę wiedzieć więcej!</a>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

                        {% endif %}


    <div class="jumbotron" style="background-color:#F8F9FA">
  <h1 class="display-4">Exhibit</h1>
  <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dignissim urna eget bibendum dapibus. Etiam vehicula quis quam id pellentesque. Cras quis ante elementum, laoreet metus quis, eleifend dui. Proin semper facilisis mi, nec sagittis nulla vulputate vitae.</p>

   <form method="get" action="{% url 'search' %}" class="form-inline my-2 my-lg-0">
      <input class="form-control mr-lg-1" id= "search-input" type="text" name="q" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" style="display:none;" type="submit">Search</button>
    </form>
</div>




<div class="container">
  <div class="row">
    <div class="gallery" id="gallery">
      {% for photo in photos %}
      <div class="mb-3 pics animation all 4">
        <a href="{% url 'detail' photo.pk %}"><img
          class=" zoom img-fluid "
          src="{{ photo.photo_file.url }}"
          alt="{{ photo.photo_title }}"

        /></a>
        {% if photo.was_published_recently %}
        <span class="badge badge-success">New! </span>
        <strong>{{ photo.photo_title }}</strong> by {{ photo.owner }},
        likes: {{ photo.photo_like }}

        {% else %}

        <br /><strong>{{ photo.photo_title }}</strong> by {{ photo.owner }}

        {% endif %}
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% else %}
<h3>empty</h3>
{% endif %} {% endblock %}

exhibit/templates/exhibit/inmail.html
{% extends 'base.html' %}

{% block content %}
{% if DoesNotExist %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>{{ username }}</strong>, taka wiadomość nie istnieje!
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
    {% endif %}
    {% if not success %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <strong>{{ username }}</strong>, witaj w nowym InMail!
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
    {% else %}

    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{ username }}</strong>, wiadomość wysłana poprawnie
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
    {% endif %}
 <div class="row">

     <div class="col-sm"></div>
     <div class="col-6">

{% if inmails %}
<div class="list-group">
          <a href="#" class="list-group-item list-group-item-action disabled"> Wiadomość od:</a>

    {% for inmail in inmails %}
        <a href="{% url 'inmail' inmail.pk %}" class="list-group-item list-group-item-action flex-column align-items-start ">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">{{ inmail.from_user }} - {{ inmail.title_txt }}</h5>
      <small>{{ inmail.send }}</small>
    </div>
{#    <p class="mb-1">{{ inmail.message_txt }}</p>#}
    <small></small>
  </a>
    {% endfor %}
</div>
{% endif %}






     <br />


     </div>
     <div class="col-sm-3">

         <h2>Wyślij wiadomość</h2>
     <div class="form-group fluid">
  <form method="post" class="post-form" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form.as_p }}
      </p>
    <button type="submit" class="btn btn-outline-success btn-block">Wyślij wiadomość</button>
  </form>
     </div>
 </div>
 <div class="col-sm"></div>
 </div>
                <script>
  $("#id_message_txt").addClass("form-control");
  $("#id_to_user").addClass("form-control");
  $("#id_title_txt").addClass("form-control");

                </script>
{% endblock %}
        </div>

exhibit/templates/exhibit/inmail_.html
{% extends 'base.html' %}

{% block content %}
    {% if not DoesNotExist %}
    <div class="container">
    <div class="row">
        <div class="col-sm-6">

            <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action disabled"> Wiadomość od:</a>

            {% for inmail in inmails %}
            <a href="{% url 'inmail' inmail.pk %}" class="list-group-item list-group-item-action flex-column align-items-start ">
            <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ inmail.from_user }} - {{ inmail.title_txt }}</h5>
            <small>{{ inmail.send }}</small>
            </div>
{#            <p class="mb-1">{{ inmail.message_txt }}</p>#}
            <small></small>
            </a>
            {% endfor %}
            </div></div>

        <div class="col-sm-6">
        <div class="card text-left">
        <div class="card-header">
        Wiadomość od użytkownika <strong>{{ inmail.from_user }}</strong>
        </div>
        <div class="card-body">
        <h5 class="card-title">Tytuł: {{ inmail.title_txt }}</h5>
        <p class="card-text">{{ inmail.message_txt }}</p>
        <a href="#" class="btn btn-outline-dark" style="display: block">Odpowiedz</a>
        </div>
        <div class="card-footer text-muted">
        {{ inmail.send }}
        </div>
        </div>
    </div>
        </div>
    </div>
</div>
    {% else %}
        <p>Nie ma takiej wiadomosci</p>

    {% endif %}

                <script>
  $("#id_message_txt").addClass("form-control");
  $("#id_to_user").addClass("form-control");
  $("#id_title_txt").addClass("form-control");

                </script>
{% endblock %}

exhibit/templates/exhibit/login.html
{% extends 'base.html' %}


            {% block content %}
 <div class="container-fluid">
 <div class="row">
     <div class="col-sm"></div>
     <div class="col-sm">
        <form method="POST">

        {% csrf_token %}
                    {% for error in form.errors %}
            <div class="alert alert-danger" role="alert">
 Uwaga
</div>
                                    <span class="text-danger small">{{ field.errors }}</span>

        {% endfor %}
        {{form.as_p}}
            <button class="btn btn-outline-dark btn-block" type="submit">Login</button>
        </form><br />
        Nie masz konta? <a href="{% url 'signup' %}" style="color:#2B2B2B" ><strong>Załóż je teraz</strong>!</a><br/><br/>
       <a href="{% url 'social:begin' 'github' %}" {% url 'social:begin' 'github' %}class="btn btn-block btn-social btn-github">
    <span class="fa fa-github"></span> Sign in with Github
  </a>

     </div>
     <div class="col-sm"></div>
 </div>
 </div>

                <script>
  $("#id_username").addClass("form-control");
  $("#id_password").addClass("form-control");

                </script>
{% endblock %}
        </div>

exhibit/templates/exhibit/newsletter.html
{% extends 'base.html' %}

{% block content %}
 <div class="container-fluid">
 <div class="row">
     <div class="col-sm"></div>
     <div class="col-sm">

         <h2>Newsletter - zapisz się</h2>
     <div class="form-group fluid">
  <form method="post" class="post-form" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form.as_p }}
      </p>
    <button type="submit" class="btn btn-outline-success btn-block">Dodaj</button>
  </form></div>



     <br />


     </div>
     <div class="col-sm"></div>
 </div>
 </div>
                <script>
  $("#id_useremail").addClass("form-control");
  $("#id_msgtitle").addClass("form-control");
  $("#id_password2").addClass("form-control");
  $("#id_msg").addClass("form-control");
                </script>
{% endblock %}
        </div>

exhibit/templates/exhibit/notlogin.html
{% extends 'base.html' %}

{% block content %}
 <div class="container-fluid">
 <div class="row">
     <div class="col-sm"></div>
     <div class="col-sm">

<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <strong>Dostęp zabrioniony.</strong> <a style="color: #721B24" href="{% url 'login' %}">Zaloguj się.</a>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>







     <br />


     </div>
     <div class="col-sm"></div>
 </div>
 </div>
                <script>
  $("#id_useremail").addClass("form-control");
  $("#id_msgtitle").addClass("form-control");
  $("#id_password2").addClass("form-control");
  $("#id_msg").addClass("form-control");
                </script>
{% endblock %}
        </div>

exhibit/templates/exhibit/results.html
{% extends 'base.html' %} {% block content %}


<div class="container">

<div class="row">
{% if users %}
<div class="alert alert-primary" role="alert" style="width: 100%">
  Użytkownicy:
</div>

<div class="card-columns">

{% for user in users %}
<div class="card">
    <div class="card-body">
        <form method="get" action="{% url 'follow' %}" class="form-inline my-2 my-lg-0">
            <h5  type="text" value="{{ user.pk }} class="card-title"> {{ user.username }} </h5><br/>
            <p class="card-text"><small class="ext-muted"> Użytkownik <strong>{{ user.username }} </strong>dołączył do <i>Exhibit</i> {{ user.date_joined }}</small></p>
            <input  class="form-control mr-lg-1" id= "search-input" type="hidden" name="f" placeholder="Search"  value="{{ user.pk }}"aria-label="Search"><br/>
            <button style="display: block" class="btn btn-outline-success my-2 my-sm-0"  type="submit" onsubmit="$('#search-input').val($('h5.card-title').attr('value'))">Obserwuj</button>
        </form>
    </div>
</div>
{% endfor %}
{% endif %}

</div>

</div>


    </div>
<div class="container">

  <div class="row">
   {% if photos %}
       <div class="alert alert-primary" role="alert" style="width: 100%">
  Zdjęcia:
</div>
    <div class="gallery" id="gallery">
      {% for photo in photos %}
      <div class="mb-3 pics animation all 4">
        <a href="{% url 'detail' photo.pk %}"><img
          class="img-fluid"
          src="{{ photo.photo_file.url }}"
          alt="{{ photo.photo_title }}"
        /></a>
        {% if photo.was_published_recently %}
        <span class="badge badge-success">New! </span>
        <strong>{{ photo.photo_title }}</strong> by {{ photo.owner }},
        likes: {{ photo.photo_like }}

        {% else %}

        <br /><strong>{{ photo.photo_title }}</strong> by {{ photo.owner }},likes: {{ photo.photo_like }}

        {% endif %}
      </div>
      {% endfor %}
    </div>
  </div>
</div>

       {% endif %}



    {%  if empty %}
<div class="container">
<div class="row">
    <div class="col-sm">
        <div class="alert alert-danger" role="alert">
  <h4 class="alert-heading">Oppps.</h4>
<p>Niestety nie znaleźliśmy tego czego szukasz</p> </div>
    </div>
</div>
</div>


{% endif %}


{% endblock %}

exhibit/templates/exhibit/success.html
{% extends 'base.html' %}

{% block content %}
 <div class="container-fluid">
 <div class="row">
     <div class="col-sm"></div>
     <div class="col-sm">

<div class="alert alert-success" role="alert">
  Wiadomość wysłana poprawnie!
</div>






     <br />


     </div>
     <div class="col-sm"></div>
 </div>
 </div>
                <script>
  $("#id_useremail").addClass("form-control");
  $("#id_msgtitle").addClass("form-control");
  $("#id_password2").addClass("form-control");
  $("#id_msg").addClass("form-control");
                </script>
{% endblock %}
        </div>